import {
  User,
  MapPin,
  GraduationCap,
  BookOpen,
  FileText,
  CheckCircle2,
} from 'lucide-react';
import { ARQUIVOS_IDENTIFICACAO } from '../../../data/cursosData';
import { DadosInscricaoFormando } from '../../../utils/securityAndValidation';

export const STORAGE_DRAFT_KEY = 'cfp_stp_inscricao_online_rascunho_v2';
export const STORAGE_HISTORICO_KEY = 'cfp_stp_inscricoes_submetidas_v2';

export const ETAPAS_WIZARD = [
  { numero: 1, titulo: 'Dados Pessoais', desc: 'Identificação e filiação', icone: User },
  { numero: 2, titulo: 'Contactos', desc: 'Morada, distrito e telefone', icone: MapPin },
  { numero: 3, titulo: 'Formação', desc: 'Habilitações e experiência', icone: GraduationCap },
  { numero: 4, titulo: 'Escolha do Curso', desc: '1.ª e 2.ª opção e motivo', icone: BookOpen },
  { numero: 5, titulo: 'Documentos', desc: 'Fotografia e anexos', icone: FileText },
  { numero: 6, titulo: 'Revisão', desc: 'Conferência antes do envio', icone: CheckCircle2 },
];

export const criarEstadoInicial = (): DadosInscricaoFormando => ({
  id: crypto.randomUUID(),
  protocolo: '',
  nome: '',
  nome_pai: '',
  nome_mae: '',
  bi: '',
  arquivo_identificacao: ARQUIVOS_IDENTIFICACAO[0],
  nif: '',
  datanascimento: '',
  idade: '',
  sexo: '',
  nacionalidade: 'Santomense',
  naturalidade: '',
  estado_civil: '',
  agregado_familiar: '1',
  morada: '',
  distrito: '',
  telefone: '',
  telefone2: '',
  email: '',
  ocupacao: '',
  habilitacao_nivel: '',
  habilitacao_classe: '',
  habilitacao_area: '',
  habilitacao: '',
  formacao_profissional: '',
  experiencia_profissional: '',
  motivo_inscricao: '',
  situacao_emprego: '',
  atividade_profissional_anterior: '',
  funcao_exerce: '',
  funcao_desde: '',
  profissao: '',
  possui_caso_especial: 'Não',
  casos_especiais: '',
  encaminhado_apoio_social: 'Não',
  instituicao_apoio_social: '',
  encaminhado_outra_instituicao: '',
  autoriza_divulgacao_dados: 'Sim',
  observacao: '',
  programa_id: '',
  programa_nome: '',
  curso_id: '',
  curso_nome: '',
  curso_acao: '',
  curso_horario: '',
  curso_local: '',
  programa_opcao_2_id: '',
  curso_opcao_2_id: '',
  curso_opcao_2_nome: '',
  curso_opcao_2_programa: '',
  curso_opcao_2_horario: '',
  curso_opcao_2_local: '',
  ano: '2026',
  situacao: 'Inscrito',
  data_inscricao: new Date().toISOString().split('T')[0],
  foto: null,
  fotoPreview: '',
  fotoDimensoes: null,
  doc_bi: null,
  doc_nif: null,
  doc_certificado_habilitacao: null,
  doc_certificado_profissional: null,
  aceita_declaracao: false,
});
